// Sample HSN/SAC reference data (small starter set; CA office can extend later)
export type HsnSeed = { code: string; type: "HSN" | "SAC"; description: string; gstRate: number };

export const HSN_SEED: HsnSeed[] = [
  { code: "0401", type: "HSN", description: "Milk and cream, not concentrated nor with sugar", gstRate: 0 },
  { code: "0701", type: "HSN", description: "Potatoes, fresh or chilled", gstRate: 0 },
  { code: "1006", type: "HSN", description: "Rice", gstRate: 5 },
  { code: "1101", type: "HSN", description: "Wheat or meslin flour", gstRate: 5 },
  { code: "1701", type: "HSN", description: "Sugar", gstRate: 5 },
  { code: "1905", type: "HSN", description: "Bread, pastry, cakes, biscuits", gstRate: 5 },
  { code: "2106", type: "HSN", description: "Food preparations not elsewhere specified", gstRate: 18 },
  { code: "2202", type: "HSN", description: "Aerated beverages", gstRate: 28 },
  { code: "2402", type: "HSN", description: "Cigars, cigarettes, tobacco products", gstRate: 28 },
  { code: "3004", type: "HSN", description: "Medicaments (mixed or unmixed)", gstRate: 12 },
  { code: "3401", type: "HSN", description: "Soap; surface-active preparations", gstRate: 18 },
  { code: "3923", type: "HSN", description: "Articles for conveyance/packing of goods, plastic", gstRate: 18 },
  { code: "4011", type: "HSN", description: "New pneumatic tyres of rubber", gstRate: 28 },
  { code: "4202", type: "HSN", description: "Trunks, suitcases, handbags", gstRate: 18 },
  { code: "4901", type: "HSN", description: "Printed books, brochures", gstRate: 0 },
  { code: "4907", type: "HSN", description: "Stamps, bank notes", gstRate: 0 },
  { code: "5208", type: "HSN", description: "Woven fabrics of cotton", gstRate: 5 },
  { code: "6101", type: "HSN", description: "Men's overcoats, knitted", gstRate: 12 },
  { code: "6109", type: "HSN", description: "T-shirts, singlets, knitted", gstRate: 12 },
  { code: "6403", type: "HSN", description: "Footwear with leather uppers", gstRate: 18 },
  { code: "7113", type: "HSN", description: "Articles of jewellery", gstRate: 3 },
  { code: "7308", type: "HSN", description: "Structures and parts of structures, iron/steel", gstRate: 18 },
  { code: "8415", type: "HSN", description: "Air conditioning machines", gstRate: 28 },
  { code: "8471", type: "HSN", description: "Automatic data-processing machines (computers)", gstRate: 18 },
  { code: "8517", type: "HSN", description: "Telephone sets, smartphones", gstRate: 18 },
  { code: "8528", type: "HSN", description: "Monitors and projectors, television receivers", gstRate: 28 },
  { code: "8703", type: "HSN", description: "Motor cars and other motor vehicles for transport of persons", gstRate: 28 },
  { code: "8711", type: "HSN", description: "Motorcycles", gstRate: 28 },
  { code: "9018", type: "HSN", description: "Medical instruments and appliances", gstRate: 12 },
  { code: "9403", type: "HSN", description: "Other furniture and parts thereof", gstRate: 18 },

  { code: "9954", type: "SAC", description: "Construction services", gstRate: 18 },
  { code: "9961", type: "SAC", description: "Wholesale trade services", gstRate: 18 },
  { code: "9963", type: "SAC", description: "Accommodation, food and beverage services", gstRate: 5 },
  { code: "9964", type: "SAC", description: "Passenger transport services", gstRate: 5 },
  { code: "9965", type: "SAC", description: "Goods transport services", gstRate: 5 },
  { code: "9971", type: "SAC", description: "Financial and related services", gstRate: 18 },
  { code: "9972", type: "SAC", description: "Real estate services", gstRate: 18 },
  { code: "9973", type: "SAC", description: "Leasing or rental services", gstRate: 18 },
  { code: "9982", type: "SAC", description: "Legal and accounting services", gstRate: 18 },
  { code: "9983", type: "SAC", description: "Other professional, technical and business services", gstRate: 18 },
  { code: "9984", type: "SAC", description: "Telecommunications, broadcasting and information supply services", gstRate: 18 },
  { code: "9987", type: "SAC", description: "Maintenance, repair and installation services", gstRate: 18 },
  { code: "9988", type: "SAC", description: "Manufacturing services on physical inputs owned by others", gstRate: 18 },
  { code: "9991", type: "SAC", description: "Public administration and other services", gstRate: 18 },
  { code: "9992", type: "SAC", description: "Education services", gstRate: 0 },
  { code: "9993", type: "SAC", description: "Human health and social care services", gstRate: 0 },
  { code: "9996", type: "SAC", description: "Recreational, cultural and sporting services", gstRate: 18 },
];
